[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[colors.primary]
foreground = '#b8b9b8'
background = '#2C2C2C'

[colors.cursor]
text = '#2C2C2C'
cursor = '#97957A'

[colors.normal]
black = "#767676"
red = "#97957A"
green = "#929496"
yellow = "#BBBAA0"
blue = "#7A7C97"
magenta = "#977A7C"
cyan = "#7C977A"
white = "#B8B9B8"

[colors.bright]
black = "#838484"
red = "#AEAC97"
green = "#AAACAD"
yellow = "#C7C6B1"
blue = "#9799AE"
magenta = "#AE9799"
cyan = "#99AE97"
white = "#D1D2D1"
