[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[colors.primary]
foreground = '#f7ece8'
background = '#322824'

[colors.cursor]
text = '#322824'
cursor = '#C4825B'

[colors.normal]
black = "#7A7370"
red = "#C4825B"
green = "#9A908B"
yellow = "#E3AA88"
blue = "#5B9DC4"
magenta = "#C45B9D"
cyan = "#9DC45B"
white = "#F7ECE8"

[colors.bright]
black = "#847E7B"
red = "#D19E7F"
green = "#B0A8A5"
yellow = "#E8B99D"
blue = "#7FB3D1"
magenta = "#D17FB3"
cyan = "#B3D17F"
white = "#FAF3F0"
