[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[colors.primary]
foreground = '#def9f0'
background = '#000200'

[colors.cursor]
text = '#000200'
cursor = '#7DE8C6'

[colors.normal]
black = "#5B5C5B"
red = "#7DE8C6"
green = "#697A74"
yellow = "#B1F1DD"
blue = "#E87D9F"
magenta = "#9FE87D"
cyan = "#7D9FE8"
white = "#DEF9F0"

[colors.bright]
black = "#636565"
red = "#9AEDD3"
green = "#8A9793"
yellow = "#BFF4E3"
blue = "#ED9AB4"
magenta = "#B4ED9A"
cyan = "#9AB4ED"
white = "#EAFBF5"
