[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors.primary]
foreground = '#f8f2ce'
background = '#111111'

[colors.cursor]
text = '#111111'
cursor = '#5E71EF'

[colors.normal]
black = "#626262"
red = "#5E71EF"
green = "#817E67"
yellow = "#ABB5F7"
blue = "#EFDC5E"
magenta = "#5EEFDC"
cyan = "#DC5EEF"
white = "#F8F2CE"

[colors.bright]
black = "#6B6B6B"
red = "#8190F3"
green = "#9D9A88"
yellow = "#BAC2F8"
blue = "#F3E481"
magenta = "#81F3E4"
cyan = "#E481F3"
white = "#FAF7DF"
