[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors.primary]
foreground = "#F7C7A1"
background = "#000000"

[colors.cursor]
text = '#000000'
cursor = '#E85D2F'

[colors.normal]
black = "#1a1210"
red = "#E85D2F"
green = "#7C8A6A"
yellow = "#FF8B4A"
blue = "#758A9B"
magenta = "#C06030"
cyan = "#9aab8a"
white = "#F7C7A1"

[colors.bright]
black = "#3D2B24"
red = "#FF6B3A"
green = "#9aab8a"
yellow = "#FF9B5A"
blue = "#949EA3"
magenta = "#FF8B4A"
cyan = "#BCC2C6"
white = "#F7C7A1"
