[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors.primary]
foreground = '#fffae5'
background = '#1D1D21'

[colors.cursor]
text = '#1D1D21'
cursor = '#F1DB74'

[colors.normal]
black = "#69696C"
red = "#F1DB74"
green = "#89857B"
yellow = "#F7E9AB"
blue = "#748AF1"
magenta = "#F1748A"
cyan = "#8AF174"
white = "#FFFAE5"

[colors.bright]
black = "#737376"
red = "#F4E393"
green = "#A3A098"
yellow = "#F8EDBA"
blue = "#93A4F4"
magenta = "#F493A4"
cyan = "#A4F493"
white = "#FFFCEE"
