// CalendarPopup.qml — calendar + pomodoro + countdown + alarm popup.
//
// Replaces: waybar/calendar/calendar.html + waybar/clock/timer-server.py +
//           launcher waybar/scripts/calendar.sh + Brave profile
//           ~/.cache/niri-clock (old app-id brave-127.0.0.4__-Default,
//           window 400x490, backend on 127.0.0.4). The Brave profile, the
//           timer-server.py daemon and the 127.0.0.4 backend are all deleted
//           by this migration; nothing else needs them.
//
// Backend parity (from timer-server.py — same schema, same file):
//   state file: $NIRI_CLOCK_DIR/state.json (default
//               ~/.cache/niri-clock/state.json), same JSON shape
//               {pomo:{phase,round,remain,running,last},
//                timer:{remain,running,last,minutes,seconds,finished},
//                alarm:{hour,minutes,enabled,repeat,lastFire},
//                cfg:{focus,short,long,rounds}} plus the active tab.
//               An old state.json left by timer-server.py is picked up and
//               caught up by wall-clock, so in-flight timers survive the
//               migration (the legacy server round-trips the unknown
//               "alarm" key untouched).
//   pomodoro chain focus->short/long->focus, rounds clamp 1-12,
//   focus 1-180min, short/long 1-60min; cmds start/pause/reset/skip.
//   countdown start(fresh seconds|resume)/pause/reset, cap 359999s.
//   alarm: single wall-clock HH:MM, one-shot or daily repeat; fires a
//   sticky critical toast + beep even with the popup closed. A set for a
//   time already past today rings tomorrow (today is marked done).
//   expiry beep via pw-play || paplay || aplay; the beep.wav generated by
//   the old server (~/.cache/niri-clock/beep.wav) is reused when present.
//
// Timing engine lives in services/PomodoroService.qml (singleton), NOT
// in this Scope: shell.qml instantiates CalendarPopup once and only flips
// isOpen, while the service ticks, chains phases, beeps + notifies with
// the popup closed — exactly like the old keep-running timer-server.py.
// Bar widgets bind to the same service for at-a-glance status.
//
// Shell contract (landed sunset pattern, cf. ClipboardPopup/Launcher):
//   - exclusiveKeyboardFocus == WlrLayershell.keyboardFocus Exclusive.
//   - Esc closes; outside-click closes; Bar re-click toggles via IPC.
//   - Card width 400 (old 400x490 window); height is content-driven.
//   - niri layer-rule doc (shell owner adds, do NOT edit rules.kdl here):
//       layer-rule { match namespace="sunset-calendar" }
//     Verify: `niri msg layers`
// IPC: `qs -c sunset ipc call calendar toggle` (also: open, close,
//   openAlarm, pomoStart, pomoPause, pomoReset, pomoSkip, timerPause,
//   alarmSet, alarmEnable, alarmDisable, alarmToggle, alarmClear)

import QtQuick
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import qs.services

Scope {
    id: root

    // Theme aliases: DayOfWeekRow/MonthGrid delegates run in the control's
    // context where file imports (Theme singleton) are invisible, so route
    // every token through root (id scope chain reaches delegates).
    readonly property color cAccent: Theme.accent
    readonly property color cAccentHover: Theme.accentHover
    readonly property color cBg: Theme.bg
    readonly property color cBorderStrong: Theme.borderStrong
    readonly property color cDim: Theme.dim
    readonly property string cFont: Theme.fontFamily
    readonly property color cMuted: Theme.muted
    readonly property color cPanel: Theme.panel
    readonly property int cRadius: Theme.radius
    readonly property color cRow: Theme.row
    readonly property color cText: Theme.text

    property bool isOpen: false
    // Task term "exclusiveKeyboardFocus" == the Exclusive layer-shell
    // keyboard focus set on the PanelWindow below.
    readonly property bool exclusiveKeyboardFocus: true

    function open(): void {
        isOpen = true;
        focusTimer.restart();
    }
    function close(): void {
        engine.saveState();
        isOpen = false;
    }
    function toggle(): void {
        if (isOpen)
            close();
        else
            open();
    }

    // Timing engine alias: all `engine.*` bindings below resolve to the
    // PomodoroService singleton (state file, tick, beep + sticky
    // notifications live there so Bar + popup stay in sync).
    readonly property var engine: PomodoroService

    // ---- calendar view state ----
    // MonthGrid.month is 1-12 (QtQuick.Controls Calendar.January == 1).
    readonly property var monthNames: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    property int viewMonth: new Date().getMonth() + 1
    property int viewYear: new Date().getFullYear()
    property string tab: "calendar"
    readonly property var tabOrder: ["calendar", "pomo", "timer", "alarm"]

    function nextTab(): void {
        const i = tabOrder.indexOf(tab);
        tab = tabOrder[(i + 1) % tabOrder.length];
        engine.saveState();
    }
    function prevTab(): void {
        const i = tabOrder.indexOf(tab);
        tab = tabOrder[(i + tabOrder.length - 1) % tabOrder.length];
        engine.saveState();
    }
    function activatePrimary(): void {
        if (tab === "calendar") {
            goToday();
        } else if (tab === "pomo") {
            engine.pomoCmd(engine.pomoRunning ? "pause" : "start");
        } else if (tab === "timer") {
            timerPrimary();
        } else if (tab === "alarm") {
            engine.alarmToggle();
        }
    }

    function shiftMonth(d: int): void {
        viewMonth += d;
        if (viewMonth < 1) {
            viewMonth = 12;
            viewYear -= 1;
        } else if (viewMonth > 12) {
            viewMonth = 1;
            viewYear += 1;
        }
    }
    function goToday(): void {
        const t = new Date();
        viewMonth = t.getMonth() + 1;
        viewYear = t.getFullYear();
    }

    SystemClock {
        id: sysClock
        // Perf: Seconds only while open (pomodoro countdown); Minutes at
        // idle saves 1 wake/s on weak CPUs.
        precision: root.isOpen ? SystemClock.Seconds : SystemClock.Minutes
    }

    // Engine + state live in PomodoroService (singleton); popup is UI only.
    Component.onDestruction: engine.saveState()

    // Re-assert keyboard focus on open (Launcher/WallpaperMenu parity).
    Timer {
        id: focusTimer
        interval: 60
        running: false
        repeat: false
        onTriggered: keys.forceActiveFocus()
    }

    PanelWindow {
        id: win
        visible: root.isOpen
        color: "transparent"
        anchors {
            top: true
            bottom: true
            left: true
            right: true
        }
        exclusiveZone: 0
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: WlrKeyboardFocus.Exclusive
        WlrLayershell.namespace: "sunset-calendar"

        MouseArea {
            anchors.fill: parent
            onClicked: root.close()
        }

        Rectangle {
            id: card
            anchors.centerIn: parent
            // Old Brave window was 400 wide; height is content-driven.
            implicitWidth: Math.min(400, parent.width - 32)
            implicitHeight: Math.min(col.implicitHeight + 26, parent.height - 48)
            width: implicitWidth
            height: implicitHeight
            color: root.cPanel
            border.width: 1
            border.color: root.cBorderStrong
            radius: root.cRadius
            // Micro-animation: subtle entrance (opacity 150ms OutCubic +
            // scale 0.96->1 180ms OutBack overshoot 1.2 + y -6->0).
            // Close stays instant (visible flips with isOpen, <200ms).
            transformOrigin: Item.Center
            scale: root.isOpen ? 1.0 : 0.96
            opacity: root.isOpen ? 1 : 0
            transform: Translate {
                y: root.isOpen ? 0 : -6
                Behavior on y {
                    NumberAnimation {
                        duration: 150
                        easing.type: Easing.OutCubic
                    }
                }
            }
            Behavior on scale {
                NumberAnimation {
                    duration: 180
                    easing.type: Easing.OutBack
                    easing.overshoot: 1.2
                }
            }
            Behavior on opacity {
                NumberAnimation {
                    duration: 150
                    easing.type: Easing.OutCubic
                }
            }

            // Steal keyboard focus on show so Esc/arrows work immediately.
            FocusScope {
                id: keys
                anchors.fill: parent
                focus: true

                Keys.onEscapePressed: root.close()
                // Tab cycles the three tabs (unless typing in a numeric
                // field, where Tab moves between fields). Kept out of
                // onPressed so Qt focus navigation never steals it.
                Keys.onTabPressed: event => {
                    const f = win.activeFocusItem;
                    if (f && f.objectName === "numEdit")
                        return;
                    event.accepted = true;
                    root.nextTab();
                }
                Keys.onBacktabPressed: event => {
                    const f = win.activeFocusItem;
                    if (f && f.objectName === "numEdit")
                        return;
                    event.accepted = true;
                    root.prevTab();
                }
                Keys.onPressed: event => {
                    // Yield to numeric/password fields (cursor keys type).
                    const f = win.activeFocusItem;
                    if (f && f.objectName === "numEdit")
                        return;
                    if (event.key === Qt.Key_Left || event.key === Qt.Key_H) {
                        if (root.tab === "calendar")
                            root.shiftMonth(-1);
                        else
                            root.prevTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_Right || event.key === Qt.Key_L) {
                        if (root.tab === "calendar")
                            root.shiftMonth(1);
                        else
                            root.nextTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_Up || event.key === Qt.Key_K) {
                        if (root.tab === "calendar")
                            root.viewYear += 1;
                        else
                            root.prevTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_Down || event.key === Qt.Key_J) {
                        if (root.tab === "calendar")
                            root.viewYear -= 1;
                        else
                            root.nextTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_PageUp) {
                        if (root.tab === "calendar")
                            root.shiftMonth(-1);
                        else
                            root.prevTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_PageDown) {
                        if (root.tab === "calendar")
                            root.shiftMonth(1);
                        else
                            root.nextTab();
                        event.accepted = true;
                    } else if (event.key === Qt.Key_Home) {
                        if (root.tab === "calendar")
                            root.goToday();
                        else
                            root.tab = "calendar";
                        event.accepted = true;
                    } else if (event.key === Qt.Key_End) {
                        if (root.tab === "calendar")
                            root.goToday();
                        else
                            root.tab = "alarm";
                        event.accepted = true;
                    } else if (event.key === Qt.Key_Return || event.key === Qt.Key_Enter || event.key === Qt.Key_Space) {
                        root.activatePrimary();
                        event.accepted = true;
                    }
                }

                Column {
                    id: col
                    anchors.fill: parent
                    anchors.margins: 18
                    anchors.topMargin: 16
                    anchors.bottomMargin: 10
                    spacing: 0

                    // ---- tab views (exactly one visible; fixed box keeps
                    // ---- card height stable across tabs) ----
                    Item {
                        id: viewsBox
                        width: parent.width
                        height: 348

                        // ===== CALENDAR =====
                        Column {
                            anchors.fill: parent
                            spacing: 0
                            visible: root.tab === "calendar"

                            Text {
                                id: clockTime
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: Qt.formatTime(sysClock.date, "hh:mm:ss")
                                font.family: root.cFont
                                font.pixelSize: 28
                                font.bold: true
                                color: root.cText
                            }
                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: Qt.formatDate(sysClock.date, "dddd, dd MMMM yyyy")
                                font.family: root.cFont
                                font.pixelSize: 12
                                color: root.cMuted
                            }
                            Item {
                                width: parent.width
                                height: 10
                            }
                            Row {
                                width: parent.width
                                height: 28
                                spacing: 4

                                Row {
                                    width: (parent.width - 4) / 2
                                    height: parent.height
                                    spacing: 4
                                    CalNavBtn {
                                        cAccent: root.cAccent
                                        cAccentHover: root.cAccentHover
                                        cFont: root.cFont
                                        cRadius: root.cRadius
                                        text: "\u2039"
                                        tip: "Previous month"
                                        onClicked: root.shiftMonth(-1)
                                    }
                                    Text {
                                        width: parent.width - 64
                                        anchors.verticalCenter: parent.verticalCenter
                                        horizontalAlignment: Text.AlignHCenter
                                        text: root.monthNames[root.viewMonth - 1]
                                        font.family: root.cFont
                                        font.pixelSize: 15
                                        font.bold: true
                                        color: root.cText
                                    }
                                    CalNavBtn {
                                        cAccent: root.cAccent
                                        cAccentHover: root.cAccentHover
                                        cFont: root.cFont
                                        cRadius: root.cRadius
                                        text: "\u203A"
                                        tip: "Next month"
                                        onClicked: root.shiftMonth(1)
                                    }
                                }
                                Row {
                                    width: (parent.width - 4) / 2
                                    height: parent.height
                                    spacing: 4
                                    CalNavBtn {
                                        cAccent: root.cAccent
                                        cAccentHover: root.cAccentHover
                                        cFont: root.cFont
                                        cRadius: root.cRadius
                                        text: "\u2039"
                                        tip: "Previous year"
                                        onClicked: root.viewYear -= 1
                                    }
                                    Text {
                                        width: parent.width - 64
                                        anchors.verticalCenter: parent.verticalCenter
                                        horizontalAlignment: Text.AlignHCenter
                                        text: root.viewYear
                                        font.family: root.cFont
                                        font.pixelSize: 15
                                        font.bold: true
                                        color: root.cText
                                    }
                                    CalNavBtn {
                                        cAccent: root.cAccent
                                        cAccentHover: root.cAccentHover
                                        cFont: root.cFont
                                        cRadius: root.cRadius
                                        text: "\u203A"
                                        tip: "Next year"
                                        onClicked: root.viewYear += 1
                                    }
                                }
                            }
                            Item {
                                width: parent.width
                                height: 8
                            }
                            DayOfWeekRow {
                                width: parent.width
                                height: 21
                                locale: Qt.locale("en_US")
                                delegate: Text {
                                    text: model.shortName
                                    horizontalAlignment: Text.AlignHCenter
                                    verticalAlignment: Text.AlignVCenter
                                    font.family: root.cFont
                                    font.pixelSize: 11
                                    font.bold: true
                                    color: root.cAccent
                                }
                            }
                            MonthGrid {
                                id: monthGrid
                                width: parent.width
                                height: 162
                                month: root.viewMonth - 1 // MonthGrid is 0-indexed; viewMonth is 1-indexed
                                year: root.viewYear
                                locale: Qt.locale("en_US")
                                delegate: Item {
                                    id: dayCell
                                    readonly property bool isToday: model.today ?? false
                                    readonly property bool isOther: model.month !== monthGrid.month
                                    Rectangle {
                                        anchors.centerIn: parent
                                        width: 40
                                        height: 24
                                        color: dayCell.isToday ? root.cAccent : "transparent"
                                        radius: root.cRadius
                                    }
                                    Text {
                                        anchors.centerIn: parent
                                        text: model.day
                                        font.family: root.cFont
                                        font.pixelSize: 13
                                        font.bold: dayCell.isToday
                                        color: dayCell.isToday ? root.cBg : (dayCell.isOther ? root.cDim : root.cText)
                                    }
                                    HoverHandler {
                                        id: dayHover
                                        enabled: !dayCell.isToday && !dayCell.isOther
                                    }
                                }
                            }
                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: "\u2190/\u2192 month \u00B7 \u2191/\u2193 year \u00B7 PgUp/Dn month \u00B7 Home today \u00B7 Tab tab \u00B7 Enter today"
                                font.family: root.cFont
                                font.pixelSize: 10
                                color: root.cMuted
                            }
                        }

                        // ===== POMODORO =====
                        Column {
                            anchors.fill: parent
                            spacing: 8
                            visible: root.tab === "pomo"

                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: engine.pomoLabel()
                                font.family: root.cFont
                                font.pixelSize: 12
                                font.bold: true
                                color: root.cAccent
                            }
                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: engine.fmt(engine.pomoRemain)
                                font.family: root.cFont
                                font.pixelSize: 52
                                font.bold: true
                                color: (!engine.pomoRunning && engine.pomoRemain <= 0) ? root.cAccent : root.cText
                            }
                            Row {
                                width: parent.width
                                spacing: 6
                                // Native progress dots (no HTML/RichText):
                                // filled accent for completed rounds, dim otherwise.
                                Repeater {
                                    model: engine.clampInt(engine.cfgRounds, 1, 12)
                                    delegate: Text {
                                        readonly property bool dotDone: (index + 1 < engine.pomoRound) || ((index + 1) === engine.pomoRound && engine.pomoPhase !== "focus")
                                        text: "\u25CF"
                                        font.family: root.cFont
                                        font.pixelSize: 12
                                        color: dotDone ? root.cAccent : root.cDim
                                    }
                                }
                            }
                            Row {
                                width: parent.width
                                spacing: 8
                                SunsetBtn {
                                    cAccent: root.cAccent
                                    cAccentHover: root.cAccentHover
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cRadius: root.cRadius
                                    cRow: root.cRow
                                    cText: root.cText
                                    primary: true
                                    label: engine.pomoRunning ? "Pause" : "Start"
                                    onClicked: engine.pomoCmd(engine.pomoRunning ? "pause" : "start")
                                }
                                SunsetBtn {
                                    cAccent: root.cAccent
                                    cAccentHover: root.cAccentHover
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cRadius: root.cRadius
                                    cRow: root.cRow
                                    cText: root.cText
                                    label: "Skip"
                                    onClicked: engine.pomoCmd("skip")
                                }
                                SunsetBtn {
                                    cAccent: root.cAccent
                                    cAccentHover: root.cAccentHover
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cRadius: root.cRadius
                                    cRow: root.cRow
                                    cText: root.cText
                                    label: "Reset"
                                    onClicked: engine.pomoCmd("reset")
                                }
                            }
                            Row {
                                width: parent.width
                                spacing: 8
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    label: "Focus min"
                                    value: engine.cfgFocus
                                    lo: 1
                                    hi: 180
                                    onAccepted2: v => {
                                        engine.applyCfg(v, engine.cfgShort, engine.cfgLong, engine.cfgRounds);
                                    }
                                }
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    label: "Short min"
                                    value: engine.cfgShort
                                    lo: 1
                                    hi: 60
                                    onAccepted2: v => {
                                        engine.applyCfg(engine.cfgFocus, v, engine.cfgLong, engine.cfgRounds);
                                    }
                                }
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    label: "Long min"
                                    value: engine.cfgLong
                                    lo: 1
                                    hi: 60
                                    onAccepted2: v => {
                                        engine.applyCfg(engine.cfgFocus, engine.cfgShort, v, engine.cfgRounds);
                                    }
                                }
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    label: "Rounds"
                                    value: engine.cfgRounds
                                    lo: 1
                                    hi: 12
                                    onAccepted2: v => {
                                        engine.applyCfg(engine.cfgFocus, engine.cfgShort, engine.cfgLong, v);
                                    }
                                }
                            }
                        }

                        // ===== COUNTDOWN =====
                        Column {
                            anchors.fill: parent
                            spacing: 8
                            visible: root.tab === "timer"

                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: "COUNTDOWN"
                                font.family: root.cFont
                                font.pixelSize: 12
                                font.bold: true
                                color: root.cAccent
                            }
                            Text {
                                width: parent.width
                                horizontalAlignment: Text.AlignHCenter
                                text: engine.fmt(engine.timerRemain)
                                font.family: root.cFont
                                font.pixelSize: 52
                                font.bold: true
                                color: (engine.timerFinished || (!engine.timerRunning && engine.timerRemain <= 0)) ? root.cAccent : root.cText
                            }
                            Row {
                                width: parent.width
                                spacing: 8
                                SunsetBtn {
                                    cAccent: root.cAccent
                                    cAccentHover: root.cAccentHover
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cRadius: root.cRadius
                                    cRow: root.cRow
                                    cText: root.cText
                                    primary: true
                                    label: engine.timerRunning ? "Pause" : "Start"
                                    onClicked: root.timerPrimary()
                                }
                                SunsetBtn {
                                    cAccent: root.cAccent
                                    cAccentHover: root.cAccentHover
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cRadius: root.cRadius
                                    cRow: root.cRow
                                    cText: root.cText
                                    label: "Reset"
                                    onClicked: engine.timerReset(inMin.fieldValue() * 60 + inSec.fieldValue())
                                }
                            }
                            Row {
                                width: parent.width
                                spacing: 8
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    id: inMin
                                    cols: 2
                                    label: "Minutes"
                                    value: engine.timerMin
                                    lo: 0
                                    hi: 999
                                    onAccepted2: v => {
                                        engine.timerMin = v;
                                        engine.timerReset(v * 60 + inSec.fieldValue());
                                    }
                                }
                                NumField {
                                    cAccent: root.cAccent
                                    cBg: root.cBg
                                    cBorderStrong: root.cBorderStrong
                                    cFont: root.cFont
                                    cMuted: root.cMuted
                                    cRadius: root.cRadius
                                    cText: root.cText
                                    id: inSec
                                    cols: 2
                                    label: "Seconds"
                                    value: engine.timerSec
                                    lo: 0
                                    hi: 59
                                    onAccepted2: v => {
                                        engine.timerSec = v;
                                        engine.timerReset(inMin.fieldValue() * 60 + v);
                                    }
                                }
                            }
                            Row {
                                width: parent.width
                                spacing: 6
                                Repeater {
                                    model: [1, 5, 10, 15, 30]
                                    SunsetBtn {
                                        cAccent: root.cAccent
                                        cAccentHover: root.cAccentHover
                                        cBg: root.cBg
                                        cBorderStrong: root.cBorderStrong
                                        cFont: root.cFont
                                        cRadius: root.cRadius
                                        cRow: root.cRow
                                        cText: root.cText
                                        cols: 5
                                        gap: 6
                                        label: modelData + "m"
                                        onClicked: {
                                            inMin.setValue(modelData);
                                            inSec.setValue(0);
                                            engine.timerReset(modelData * 60);
                                        }
                                    }
                                }
                            }
                        }
                    }

                    // ---- bottom navbar ----
                    Item {
                        width: parent.width
                        height: 12
                    }
                    Rectangle {
                        width: parent.width
                        height: 1
                        color: root.cBorderStrong
                    }
                    Row {
                        width: parent.width
                        height: 46
                        TabBtn {
                            cAccent: root.cAccent
                            cDim: root.cDim
                            cFont: root.cFont
                            glyph: "󰸗"
                            label: "CALENDAR"
                            active: root.tab === "calendar"
                            onClicked: {
                                root.tab = "calendar";
                                engine.saveState();
                            }
                        }
                        TabBtn {
                            cAccent: root.cAccent
                            cDim: root.cDim
                            cFont: root.cFont
                            glyph: "󰄉"
                            label: "POMODORO"
                            active: root.tab === "pomo"
                            onClicked: {
                                root.tab = "pomo";
                                engine.saveState();
                            }
                        }
                        TabBtn {
                            cAccent: root.cAccent
                            cDim: root.cDim
                            cFont: root.cFont
                            glyph: "󰔟"
                            label: "TIMER"
                            active: root.tab === "timer"
                            onClicked: {
                                root.tab = "timer";
                                engine.saveState();
                            }
                        }
                    }
                }
            }
        }

        onVisibleChanged: {
            if (visible)
                focusTimer.restart();
        }
    }

    // Pomo round count helper (dots render natively in the Row above).
    function pomoDoneCount(): int {
        const rounds = engine.clampInt(engine.cfgRounds, 1, 12);
        let n = 0;
        for (let i = 1; i <= rounds; ++i) {
            if ((i < engine.pomoRound) || (i === engine.pomoRound && engine.pomoPhase !== "focus"))
                n++;
        }
        return n;
    }

    function timerPrimary(): void {
        if (engine.timerRunning) {
            engine.timerPause();
            return;
        }
        const setSecs = engine.timerMin * 60 + engine.timerSec;
        const wantSecs = inMin.fieldValue() * 60 + inSec.fieldValue();
        if (engine.timerRemain > 0 && wantSecs === setSecs)
            engine.timerStart(0); // resume paused countdown
        else
            engine.timerStart(wantSecs); // fresh start from inputs
    }

    // Small building blocks (file-local; shared popup patterns).
    component CalNavBtn: Rectangle {
        // injected props (inline component scope is isolated)
        property color cAccent: root.cAccent
        property color cAccentHover: root.cAccentHover
        property string cFont: root.cFont
        property int cRadius: 0
        id: navBtn
        property alias text: navLabel.text
        property string tip: ""
        signal clicked
        width: 28
        height: 28
        color: "transparent"
        border.width: 1
        border.color: navHover.hovered ? cAccent : "transparent"
        radius: cRadius
        transformOrigin: Item.Center
        scale: navMouse.pressed ? 0.98 : 1.0
        Behavior on scale {
            NumberAnimation {
                duration: 100
                easing.type: Easing.OutQuad
            }
        }
        Behavior on color {
            ColorAnimation {
                duration: 120
            }
        }
        ToolTip.visible: tip !== "" && navHover.hovered
        ToolTip.text: tip
        Text {
            id: navLabel
            anchors.centerIn: parent
            font.family: cFont
            font.pixelSize: 16
            font.bold: true
            color: navHover.hovered ? cAccentHover : cAccent
        }
        HoverHandler {
            id: navHover
        }
        MouseArea {
            id: navMouse
            anchors.fill: parent
            hoverEnabled: true
            onClicked: navBtn.clicked()
        }
    }

    component SunsetBtn: Rectangle {
        // injected props (inline component scope is isolated)
        property color cAccent: root.cAccent
        property color cAccentHover: root.cAccentHover
        property color cBg: root.cBg
        property color cBorderStrong: root.cBorderStrong
        property string cFont: root.cFont
        property int cRadius: 0
        property color cRow: root.cRow
        property color cText: root.cText
        id: sBtn
        property string label: ""
        property bool primary: false
        // Equal-split sizing inside a Row: cols = siblings, gap = spacing.
        property int cols: 3
        property real gap: 8
        signal clicked
        width: parent ? (parent.width - (cols - 1) * gap) / cols : 100
        height: 32
        color: primary ? cAccent : cRow
        border.width: 1
        border.color: primary ? cAccent : cBorderStrong
        radius: cRadius
        transformOrigin: Item.Center
        scale: sMouse.pressed ? 0.98 : 1.0
        Behavior on scale {
            NumberAnimation {
                duration: 100
                easing.type: Easing.OutQuad
            }
        }
        Behavior on color {
            ColorAnimation {
                duration: 120
            }
        }
        Text {
            anchors.centerIn: parent
            text: sBtn.label
            font.family: cFont
            font.pixelSize: 12
            font.bold: true
            color: primary ? cBg : (sHover.hovered ? cAccentHover : cText)
        }
        HoverHandler {
            id: sHover
        }
        MouseArea {
            id: sMouse
            anchors.fill: parent
            hoverEnabled: true
            onClicked: sBtn.clicked()
        }
    }

    component TabBtn: Rectangle {
        // injected props (inline component scope is isolated)
        property color cAccent: root.cAccent
        property color cDim: root.cDim
        property string cFont: root.cFont
        id: tBtn
        property string glyph: ""
        property string label: ""
        property bool active: false
        signal clicked
        width: parent ? parent.width / 3 : 100
        height: 46
        color: "transparent"
        transformOrigin: Item.Center
        scale: tMouse.pressed ? 0.98 : 1.0
        Behavior on scale {
            NumberAnimation {
                duration: 100
                easing.type: Easing.OutQuad
            }
        }
        Behavior on color {
            ColorAnimation {
                duration: 120
            }
        }
        Column {
            anchors.centerIn: parent
            spacing: 2
            Text {
                anchors.horizontalCenter: parent.horizontalCenter
                text: tBtn.glyph
                font.family: cFont
                font.pixelSize: 17
                color: tBtn.active ? cAccent : cDim
            }
            Text {
                anchors.horizontalCenter: parent.horizontalCenter
                text: tBtn.label
                font.family: cFont
                font.pixelSize: 11
                font.bold: true
                color: tBtn.active ? cAccent : cDim
            }
        }
        HoverHandler {
            id: tHover
        }
        MouseArea {
            id: tMouse
            anchors.fill: parent
            hoverEnabled: true
            onClicked: tBtn.clicked()
        }
    }

    component NumField: Column {
        // injected props (inline component scope is isolated)
        property color cAccent: root.cAccent
        property color cBg: root.cBg
        property color cBorderStrong: root.cBorderStrong
        property string cFont: root.cFont
        property color cMuted: root.cMuted
        property int cRadius: 0
        property color cText: root.cText
        id: nField
        property string label: ""
        property int value: 0
        property int lo: 0
        property int hi: 100
        property int cols: 4
        property real gap: 8
        signal accepted2(int v)
        function fieldValue(): int {
            return nInput.fieldValue();
        }
        function setValue(v: int): void {
            nInput.setValue(v);
        }
        width: parent ? (parent.width - (cols - 1) * gap) / cols : 70
        spacing: 3
        Text {
            width: parent.width
            horizontalAlignment: Text.AlignHCenter
            text: nField.label
            font.family: cFont
            font.pixelSize: 10
            color: cMuted
        }
        TextField {
            id: nInput
            objectName: "numEdit"
            width: parent.width
            horizontalAlignment: TextInput.AlignHCenter
            text: String(nField.value)
            font.family: cFont
            font.pixelSize: 13
            color: cText
            inputMethodHints: Qt.ImhDigitsOnly
            validator: IntValidator {
                bottom: nField.lo
                top: nField.hi
            }
            background: Rectangle {
                color: cBg
                border.width: 1
                border.color: nInput.activeFocus ? cAccent : cBorderStrong
                radius: cRadius
            }
            onAccepted: {
                nField.accepted2(fieldValue());
                focus = false;
            }
            function fieldValue(): int {
                const v = parseInt(text);
                return isNaN(v) ? nField.lo : Math.max(nField.lo, Math.min(nField.hi, v));
            }
            function setValue(v: int): void {
                text = String(v);
            }
        }
    }

    IpcHandler {
        target: "calendar"

        function toggle(): void {
            root.toggle();
        }
        function open(): void {
            root.open();
        }
        function close(): void {
            root.close();
        }
        // Direct pomo/timer control (bar widget, keybinds, scripts).
        // No auto-open: status + sticky toasts already surface progress.
        function pomoStart(): void {
            engine.pomoCmd("start");
        }
        function pomoPause(): void {
            engine.pomoCmd("pause");
        }
        function pomoReset(): void {
            engine.pomoCmd("reset");
        }
        function pomoSkip(): void {
            engine.pomoCmd("skip");
        }
        function timerPause(): void {
            engine.timerPause();
        }
    }
}
